# NOTE: this is only meant to be used in development, not production

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # run python unbuffered so debug print commands are visible immediately in docker log
    command: python -u run.py -s
    ports:
      - 80:5000
    environment:
      SQLALCHEMY_DATABASE_URI: postgres://rhizo:rhizo@postgres
      AUTOLOAD_EXTENSIONS: 'true'
    # example of linking to an extension that is in a sibling folder
    #volumes:
    #  - ../flow-server:/rhizo-server/extensions/flow-server
    depends_on:
      - postgres
  postgres:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: rhizo
      POSTGRES_USER:     rhizo
      POSTGRES_DB:       rhizo
    ports:
      - 5432
    command: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: